CREATE TABLE if NOT EXISTS Ganre (
	id SERIAL PRIMARY key,
	Title VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS Artist (
	id SERIAL PRIMARY KEY,
	Nickname VARCHAR(60) NOT NULL,
	Ganre_ID INT NOT NULL REFERENCES Ganre (id)
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY,
	Title VARCHAR(60) NOT NULL,
	Year_ SMALLINT NOT null
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY,
	Name_ VARCHAR(60) NOT NULL,
	Time_ TIME NOT NULL,
	Album_ID INT NOT NULL REFERENCES Album (id)
);

CREATE TABLE IF NOT EXISTS Tracklist (
	id SERIAL PRIMARY KEY,
	Title VARCHAR(60) NOT NULL,
	Year_ SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS Ganre_Artist (
	id SERIAL PRIMARY KEY,
	Ganre_id INT REFERENCES Ganre (id),
	Artist_id INT REFERENCES Artist (id)
);

CREATE TABLE IF NOT EXISTS Artist_Album (
	id SERIAL PRIMARY KEY,
	Artist_id INT REFERENCES Artist (id),
	Album_id INT REFERENCES Album (id)
);

CREATE TABLE IF NOT EXISTS Track_Tracklist (
	id SERIAL PRIMARY KEY,
	Track_id INT REFERENCES Track (id),
	Tracklist_id INT REFERENCES Tracklist (id)
);